global using Ardalis.SharedKernel;
global using Ardalis.Specification.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using RegistrationService.Core.Entities;
global using RegistrationService.Core.Interfaces;
global using RegistrationService.Infrastructure.Data;
